apiVersion: batch/v1
kind: Job
metadata:
  name: init-web-content
spec:
  template:
    spec:
      containers:
      - name: writer
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - echo "<h1>LSC LAB 6 WŁADYSŁAW NIEĆ</h1>" > /mnt/nfs/index.html;
        volumeMounts:
        - name: web-content
          mountPath: /mnt/nfs
      restartPolicy: OnFailure
      volumes:
      - name: web-content
        persistentVolumeClaim:
          claimName: nfs-pvc
